#!/bin/bash
# chkconfig: 345 90 10
# description: route53-register

# Set Variables
REGION=`curl -s http://169.254.169.254/latest/meta-data/local-hostname | cut -d '.' -f2`
INSTANCE_IDS=`curl -s http://169.254.169.254/latest/meta-data/instance-id/`
HOST_NAME=`aws ec2 describe-instances --region ${REGION} --instance-ids ${INSTANCE_IDS} | jq -r '.Reservations[].Instances[].Tags[] | select(.Key == "Name")' | jq -r .Value`
IP_ADDRESS=`curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
HOSTED_ZONE_ID=`aws route53 list-hosted-zones | jq -r '.HostedZones[] | select(.Name == "local.")' | jq -r .Id | awk -F/ '{print $3}'`

# Set json
BATCH_JSON='{
  "Changes": [
    { "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "'${HOST_NAME}'.local.",
        "Type": "A",
        "TTL" : 60,
        "ResourceRecords": [
          { "Value": "'${IP_ADDRESS}'" }
        ]
      }
    }
  ]
}'

# main
aws route53 change-resource-record-sets --hosted-zone-id ${HOSTED_ZONE_ID}  --change-batch "${BATCH_JSON}"

echo 0
